handler: app/handlers/load-data/handler.main
memorySize: 1024
description: Populate dynamo table with statements and transactions
timeout: 90

environment:
  FINANCIAL_TRANSACTIONS_TABLE_NAME: !Ref FinancialTransactionsTable

url: true

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
    Resource:
      - !GetAtt FinancialTransactionsTable.Arn
