handler: app/handlers/report/handler.main
memorySize: 256
description: Reports of financial statements
timeout: 30

environment:
  FINANCIAL_TRANSACTIONS_TABLE_NAME: !Ref FinancialTransactionsTable

url:
  cors: true

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:DeleteItem
    Resource:
      - !GetAtt FinancialTransactionsTable.Arn
