handler: app/handlers/ws/handler.main
memorySize: 256
description: CRUD of statements and transactions
timeout: 30

environment:
  FINANCIAL_TRANSACTIONS_TABLE_NAME: !Ref FinancialTransactionsTable

events:
  - http:
      path: /{proxy+}
      method: any
      private: true
      cors: true

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:Query
      - dynamodb:DeleteItem
    Resource:
      - !GetAtt FinancialTransactionsTable.Arn
      - !Join
        - "/"
        - - !GetAtt FinancialTransactionsTable.Arn
          - "index/*"
